name: Deploy to AUR

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "aur/**"

concurrency:
  group: aur_deployment
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
        with:
          pkgname: hyprwallhaven-git
          pkgbuild: ./aur/PKGBUILD
          commit_username: GitHub Actions
          commit_email: actions@github.com
          ssh_private_key: ${{ secrets.AUR_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
